/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleproject;

public class App {
	public String getGreeting() {
		return "Programm start!";
	}

	public static void main(String[] args) {
		System.out.println(new App().getGreeting());

		Scanner scanner = new Scanner(System.in);

		System.out.println("enter a number from 1-100k for total balls");
		int nums = scanner.nextInt(100000);
		System.out.println("enter a number from 1-100k for picking balls");
		int pickNums = scanner.nextInt(100000);

		ArrayList<Integer> totalBalls = new ArrayList<>();
		for (int i = 1; i < nums; i++) {
			totalBalls.add(i);
		}

		ArrayList<Integer> randomGetBalls = new ArrayList<>();
		for (int i = 0; i < pickNums; i++) {
			int value =new Random().nextInt(totalBalls.size() + 1);
			totalBalls.remove(value);
			randomGetBalls.add(value);
		}
		

	}

	public int GetOneNumber() {

	}
}
