spring:
  datasource:
   driver-class-name: org.h2.Driver
   url: jdbc:h2:mem:test:MODE=MySQL;DB_CLOSE_DELAY=-1 #mem 代表著預設是以 Memory-Base 的方式建立 H2資料庫。
   initialize : true
   sql-script-encoding: UTF-8
   
  jpa:
   show-sql: true
   #http://127.0.0.1:8080/h2-console/
  #spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
   hibernate.naming.physical-strategy:
     org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      settings:
        web-admin-password: sa
      enabled: true    
      
  thymeleaf:
    cache: false
    prefix: "classpath:/templates/"  #此路徑用來指定resources底下的受thymeleaf控管的物件
    suffix: ".html"
    
  Security:
    user:
     name: admin
     password: admin
#server:
#    error:
#     include-message: always     
    
 

   
